
import { AppData, Language } from './types';

export const ADMIN_USERNAME = "sivali";
export const ADMIN_PASSWORD = "sivali";

export const FONT_OPTIONS = [
  { value: "'Poppins', 'Noto Sans Myanmar', sans-serif", label: "Poppins (Default)" },
  { value: "'Noto Sans Myanmar', sans-serif", label: "Noto Sans Myanmar" },
  { value: "'Padauk', sans-serif", label: "Padauk" },
];

export const INITIAL_DATA: AppData = {
  courses: [
    {
      id: 'c1',
      title: 'Introduction to Pali Grammar',
      teacher: 'Dr. Sivali',
      telegramLink: 'https://t.me/examplechannel',
      date: '2024-07-20',
      description: 'A beginner-friendly course on the basics of Pali grammar.'
    },
  ],
  posts: [
    {
      id: 'p1',
      content: 'Welcome to the Pali Speaking platform! New courses will be announced soon. Stay tuned!',
      imageUrl: 'https://picsum.photos/800/400',
      date: '2024-07-19',
    },
  ],
  teachers: [{ id: 't1', name: 'Dr. Sivali', bio: 'Expert in Pali and Buddhist studies with over 20 years of teaching experience.' }],
  schedule: [{ id: 's1', day: 'Saturday', time: '10:00 AM - 11:30 AM', topic: 'Pali Conversation Practice' }],
  courseHistory: 'This platform was established in 2024 to promote the learning and speaking of the Pali language globally. Our mission is to make Pali accessible to everyone.',
  contactViber: '+1234567890',
};


export const LOCALES: Record<Language, Record<string, string>> = {
  [Language.English]: {
    appName: "Pāḷi Speaking",
    welcomeMessage: "Welcome to the Pāḷi Speaking Course",
    courses: "Courses",
    teachers: "Teachers",
    schedule: "Schedule",
    posts: "Posts",
    history: "Course History",
    contact: "Contact",
    adminLogin: "Admin Login",
    login: "Login",
    username: "Username",
    password: "Password",
    enterUsername: "Please enter a name to begin",
    enter: "Enter",
    searchByTeacher: "Search by teacher name...",
    searchByDate: "Search by date...",
    viewOnTelegram: "View on Telegram",
    dayMode: "Day Mode",
    darkMode: "Dark Mode",
    language: "Language",
    viberContact: "Contact us on Viber:",
    adminDashboard: "Admin Dashboard",
    manageContent: "Manage all website content from here.",
    manageCourses: "Manage Courses",
    managePosts: "Manage Posts",
    manageTeachers: "Manage Teachers",
    manageSchedule: "Manage Schedule",
    manageHistory: "Manage Course History",
    manageContact: "Manage Contact Info",
    manageSettings: "Website Settings",
    siteFont: "Site Font",
    uploadFontFile: "Upload Font File",
    saveChanges: "Save Changes",
    addNew: "Add New",
    edit: "Edit",
    delete: "Delete",
    title: "Title",
    teacher: "Teacher",
    telegramLink: "Telegram Link",
    date: "Date",
    description: "Description",
    content: "Content",
    imageUrl: "Image URL (optional)",
    name: "Name",
    bio: "Bio",
    day: "Day",
    time: "Time",
    topic: "Topic",
    viberNumber: "Viber Number",
    logout: "Logout",
    installApp: "Install App",
    installInstructions: "To install, use the 'Add to Home Screen' option in your browser's menu.",
    close: "Close",
    notificationTitle: "New Update!",
    newPostNotification: "A new post has been added.",
    newCourseNotification: "A new course has been added.",
  },
  [Language.Myanmar]: {
    appName: "ပါဠိစကားပြော",
    welcomeMessage: "ပါဠိစကားပြောသင်တန်းက ကြိုဆိုပါတယ်",
    courses: "သင်တန်းဗီဒီယို",
    teachers: "ဆရာစာရင်း",
    schedule: "သင်တန်းအချိန်စာရင်း",
    posts: "ပိုစ်များ",
    history: "သင်တန်းသမိုင်း",
    contact: "ဆက်သွယ်ရန်",
    adminLogin: "အတ်ဒမင်",
    login: "လော့ဂင်ဝင်ရန်",
    username: "အသုံးပြုသူအမည်",
    password: "စကားဝှက်",
    enterUsername: "စတင်ရန် သင်၏အမည်ကိုထည့်ပါ",
    enter: "ဝင်ရန်",
    searchByTeacher: "ဆရာအမည်ဖြင့်ရှာပါ...",
    searchByDate: "ရက်စွဲဖြင့်ရှာပါ...",
    viewOnTelegram: "တယ်လီဂရမ်တွင်ကြည့်ရန်",
    dayMode: "နေ့မုဒ်",
    darkMode: "ညမုဒ်",
    language: "ဘာသာစကား",
    viberContact: "Viber တွင် ဆက်သွယ်ရန်:",
    adminDashboard: "အတ်ဒမင် ဒက်ရှ်ဘုတ်",
    manageContent: "ဝဘ်ဆိုဒ်ပါ အကြောင်းအရာအားလုံးကို ဤနေရာမှ စီမံပါ။",
    manageCourses: "သင်တန်းများ စီမံရန်",
    managePosts: "ပိုစ်များ စီမံရန်",
    manageTeachers: "ဆရာများ စီမံရန်",
    manageSchedule: "အချိန်စာရင်း စီမံရန်",
    manageHistory: "သင်တန်းသမိုင်း စီမံရန်",
    manageContact: "ဆက်သွယ်ရန် အချက်အလက် စီမံရန်",
    manageSettings: "ဝဘ်ဆိုဒ် ဆက်တင်များ",
    siteFont: "ဝဘ်ဆိုဒ် ဖောင့်",
    uploadFontFile: "ဖောင့်ဖိုင်လ် တင်ရန်",
    saveChanges: "သိမ်းဆည်းရန်",
    addNew: "အသစ်ထည့်ရန်",
    edit: "ပြင်ရန်",
    delete: "ဖျက်ရန်",
    title: "ခေါင်းစဉ်",
    teacher: "ဆရာ",
    telegramLink: "တယ်လီဂရမ်လင့်ခ်",
    date: "ရက်စွဲ",
    description: "အကြောင်းအရာ",
    content: "အကြောင်းအရာ",
    imageUrl: "ဓာတ်ပုံလင့်ခ် (ထည့်ချင်မှထည့်ပါ)",
    name: "အမည်",
    bio: "ကိုယ်ရေးအကျဉ်း",
    day: "နေ့",
    time: "အချိန်",
    topic: "အကြောင်းအရာ",
    viberNumber: "Viber နံပါတ်",
    logout: "ထွက်ရန်",
    installApp: "အင်စတောတင်ပါ",
    installInstructions: "အင်စတောလုပ်ရန် သင့်ဘရောက်ဇာ၏ မီနူးမှ 'Add to Home Screen' ကို အသုံးပြုပါ။",
    close: "ပိတ်ရန်",
    notificationTitle: "အသစ်တင်သည်!",
    newPostNotification: "ပိုစ်အသစ်တစ်ခု တင်ထားပါသည်။",
    newCourseNotification: "သင်တန်းအသစ်တစ်ခု တင်ထားပါသည်။",
  },
};
